[package]
    name = "mxyz-engine"
    authors = ["Vincent C. Mader <vincent@mader.xyz>"]
    edition = "2018"
    version = "0.1.0"

[dependencies]
    # mxyz-utils = { path="../mxyz-utils" }
    serde_json = "1.0"

[dependencies.serde]
    version = "1.0"
    features = ["derive"]
